### ISSUE TITLE
created /etc/netowkr/if-up.d files not run on ifup

### ISSUE THREAD

**Issue by go8ose** [kernel23/puppet-iproute2#1]
It seems that beacuse these files aren't executable, ifup doesn't run them when you bring up the interface.

The patch to fix this is easy:

--- a/manifests/routes.pp
+++ b/manifests/routes.pp
@@ -16,7 +16,7 @@
             file { '/etc/network/if-up.d/iproute2-001-routes':
             ensure  => present,
             content => template('iproute2/etc/network/if-up.d/iproute2-001-routes-Debian.erb'),
-            mode    => '0644',
-            mode    => '0755',
           owner   => 'root',
           group   => 'root',
       }
  --- a/manifests/rules.pp
  +++ b/manifests/rules.pp
  @@ -16,7 +16,7 @@
           file { '/etc/network/if-up.d/iproute2-002-rules':
           ensure  => present,
           content => template('iproute2/etc/network/if-up.d/iproute2-002-rules-Debian.erb'),
-            mode    => '0644',
-            mode    => '0755',
           owner   => 'root',
           group   => 'root',
       }

**Comment by tvass** [comment]
I am sorry i did not notice your fix. I'll do ASAP.

**Comment by tvass** [comment]
Fixed.
