### ISSUE TITLE
multiple ip rule entries

### ISSUE THREAD

**Issue by go8ose** [kernel23/puppet-iproute2#2]
The /etc/network/if-up/\* scripts are called once for each network interface going up. In my case (on a machine with lo, eth0 and eth1) it means I get three identical 'ip rule' entries in 'ip rule list'.

Perhaps you should an "interface" parameter, and then have the scripts check environment variables to see if they are being called for that interface. You might even be able to implement if-down scripts in that case.

**Comment by HenluStarke** [comment]
Hi there go8ose, this should be resolved in https://github.com/kernel23/puppet-iproute2/commit/859030b07a125e76d8484b8dc064bfb0a13c00b3, please have a look and let us know.

**Comment by tvass** [comment]
Thanks.
